### ISSUE TITLE
Online mode problem

### ISSUE THREAD

**Issue by ptailyyy** [OpenNFT/OpenNFT#1]
When I used the Offline mode, the OpenNFT worked very well, e.g. NF_PSC in OpenNFT_DemoData. But if I unchecked the Offline mode and send the same demodata files to the watch folder in every 2 seconds, the OpenNFT software did not worked, and exported errors  that in the .txt file in the attachment. The operating environment is MS Windows 10 64bit, Matlab 2017a, SPM 12, Python 3.5. Following the OpenNFT_Manual, the other toolboxes are installed, and the version details are in the .jpg file in the attachment. Thank you very much. 

[errors.txt](https://github.com/OpenNFT/OpenNFT/files/1603612/errors.txt)
![version](https://user-images.githubusercontent.com/35071281/34568328-651fd174-f1a0-11e7-88c9-c221c56e8dff.JPG)

**Comment by ptailyyy** [comment]
When I added the codes, it cannot pass the compile, and exported:
Traceback (most recent call last):
    File “c:/OpenNFT/OpenNFT.py”, line 58, in <module>
        import ptbscreen
    File “c:/OpenNFT/ptbscreen.py”, line 15, in <module>
        import eventrecorder as erd
    File “c:/OpenNFT/eventrecorder.py”, line 63, in <module>
        position = int(position)
                    ^
IndentationError: expected an indented block
Process finished with exit code 1

**Comment by da0c** [comment]
If you added only the changed lines of code, you may break python indentions.
Try download whole file https://github.com/OpenNFT/OpenNFT/blob/master/eventrecorder.py

**Comment by ptailyyy** [comment]
Thanks a lot, it is passed the compile. But the online mode problem is not addressed yet. The errors exported is not change.

**Comment by da0c** [comment]
This is strange. Please, could you provide the error log?

**Comment by ptailyyy** [comment]
Setup finished: 11.43 s
*** Started ***
Searching for .dcm in C:\_RT\rtData\NF_PSC\NF_Run_1
instruction + 1
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\OpenNFT\OpenNFT_venv\lib\site-packages\watchdog-0.8.3-py3.5.egg\watchdog\observers\api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\OpenNFT\OpenNFT_venv\lib\site-packages\watchdog-0.8.3-py3.5.egg\watchdog\observers\api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "C:\OpenNFT\OpenNFT_venv\lib\site-packages\watchdog-0.8.3-py3.5.egg\watchdog\events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "C:/OpenNFT/OpenNFT.py", line 96, in on_created
    self.recorder.recordEvent(Times.t1, 0)
  File "C:\OpenNFT\eventrecorder.py", line 71, in recordEvent
    self.records[eventNumber, position] = value
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by da0c** [comment]
Update eventrecorder.py with recent commit, and try it.

**Comment by ptailyyy** [comment]
It worked, thanks a lot.

**Comment by da0c** [comment]
Fine!

**Comment by ptailyyy** [comment]
For the demo data, when I use the Offline mode it worked very well, but if I unchecked the Offline mode, and send the same DCM file to the watch folder in every 2 seconds, the OpenNFT software did not worked, likely did not receive the data ( in the Review Parameters page displayed "MRI Watch Folder exists. First file does not exist." ), and no errors exported. I was wondering if you could provide some more details or methods to solve this problem. Thank you for your time.

**Comment by da0c** [comment]
We will check the problem, thank you

**Comment by da0c** [comment]
Probably, the problem is in your file name template, please, carefully check it.
If it still will not work, you could attach your .ini file and full path to your .DCM file here, and we'll also check  it.

**Comment by ptailyyy** [comment]
![ini](https://user-images.githubusercontent.com/35071281/45264498-123b1980-b470-11e8-8871-2ffdc653352e.PNG)
![opennft](https://user-images.githubusercontent.com/35071281/45264509-4adaf300-b470-11e8-8e74-13e744e1505a.PNG)
Here is the .ini file and the OpenNFT setup parameters, it is original from the Demo. Thank you.

**Comment by da0c** [comment]
Actually the problem was in filemask processing. I hope, it is now fixed.
Let me know, does it work for you.

**Comment by da0c** [comment]
Fine! Thank you for finding this issue.
