### ISSUE TITLE
Multi-installations on same machine

### ISSUE THREAD

**Issue by ngs5** [OpenNFT/OpenNFT#11]
Good day,

Small issue is that if installing 2 separate virtual environments and (tuned/personalised) installations of OpenNFT on the same machine (e.g. same Windows session, but different virtual environments and folders), both installations seem not to be 100% independent, as some variables (e.g. paths in settings, etc.) seem to be saved in a way that is shared between the installations.

This is of course not a big problem as it does not seem to impede personalised settings but as a matter of logic, we'd appreciate a quick fix.

With best wishes,
NG

**Comment by ykoush** [comment]
For the first time, the settings will be lost due to their different storage and you will need to re-configure the settings.
