### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by seralouk** [OpenNFT/OpenNFT#112]
Hi there,

I have successfully installed the OpenNFT software and I have run the tutorials (PSC cont, SVM).
Some suggestions:

**Suggestions:**
1. In Paragraph "Real-time exported files not found in watch folder" [here](https://opennft.readthedocs.io/en/latest/troubleshooting.html) there is a mistake. `{Project Name}/{Subject ID}/{NR Run No:03}_{Image Series No:06}_{#:06}.dcm` should be `{Project Name}/{Subject ID}/{NF Run No:03}_{Image Series No:06}_{#:06}.dcm` otherwise an error is raised.
2. In the `testRTexp.py` python code that is used to mimic the real-time acquisition, I had to modify the code because I use a Mac and a) files like .DS_Store were copied, and b) the copying of the files was not correct since files are not ordered in `filelist`. So, without `sorted()` the first scan that is going to be copied, it might not be the correct one (in chronological order).
I suggest the following 2 modifications (sorted(), & (not filename.startswith(".")):):
```
for filename in sorted(filelist):
    src = os.path.join(srcpath, filename)
    if os.path.isfile(src) & (not filename.startswith(".")):
        dst = os.path.join(dstpath, filename)
        shutil.copy(src, dst)
        print(filename)
        sleep(pause_in_sec) # seconds
```

**Comment by espdev** [comment]
Hi @seralouk,

Thanks for your suggestions. However, about 2, it is preferable to use `pathlib` instead of `os.path` in modern Python. `pathlib` std module allows you to write a higher-level, laconic and understandable code.

**Comment by ykoush** [comment]
You can make a PR then, thanks.
