### ISSUE TITLE
dicomread

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#115]
I have issues with MATLAB's `dicomread`, as it can often see the file fragmented and tries to read data several magnitudes larger than the original data. It happens mostly with multiband EPI.
I wonder whether anyone else also experienced this issue and whether substituting `dicomread` with (modified) SPM function might be a solution.

**Comment by ykoush** [comment]
May be you could show a comparative screenshot, thanks.

**Comment by tiborauer** [comment]
What screenshots do you mean? About the OpenNFT running? Under which conditions?

**Comment by tiborauer** [comment]
I wrote an `spm_dicom_read`, which is a stripped-down version of `spm_dicom_convert`. It is ca. 20ms slower than `dicomread`.

**Comment by ykoush** [comment]
I mean screenshot(s) to see this "the file fragmented and tries to read data several magnitudes larger than the original data". What is fragmented file, and why it reads it with larger amplitude. This is not necessarily for openNFT screenshot, I think it is just dicomread() and this could be e.g. imshow() figures to compare. It would be also good to know which multiband EPI causes the problem, you can also share a file and we can try to reproduce. Also this may depend on dicomread() version.

**Comment by tiborauer** [comment]
I think the MATLAB warning message is misleading. "Magnitude" refers to the amount of data and not the signal intensity. It may happen when the header is not read properly (due to file fragmentation), and MATLAB tries to read more image data than the size of the file.
I am afraid I could not reproduce the issue. I think it has been due to some network or whatever file IO issue which may or may not be present. MATLAB's `dicomread` is blazing fast, and I think it may sacrifice robustness for speed.
