### ISSUE TITLE
Why no GUI pop up when I input "opennft" in the terminal?

### ISSUE THREAD

**Issue by brainwatcher** [OpenNFT/OpenNFT#118]
I am trying to install opennft on my windows 10-64 bit computer. I follow the pipeline in the [https://opennft.readthedocs.io/en/latest/install.html](install guide). I check the pip list. I thought I had installed all the dependency packages as below. But when I input `opennft` in the virtual environment terminal to initial the GUI, it only pops up a "running" blue circle near my cursor. Several seconds later, the blue circle disappeared the nothing happend.  No GUI came out. Could you help me what I missed to install it? What else do I need to do? 
This is my installation command.
`cd  C:\Users\psylab706\Documents\MATLAB\ZW\openNFT`

`py -3 -m venv opennft-venv`

`opennft-venv\Scripts\activate.bat`

`python -m pip install -U pip setuptools wheel`

`pip install git+https://github.com/OpenNFT/OpenNFT.git`

This is output of my check.
`(opennft-venv) C:\Users\psylab706\Documents\MATLAB\ZW\openNFT>pip list`

Package               Version
--------------------- --------
colorama              0.4.4
cycler                0.10.0
keyboard              0.13.5
kiwisolver            1.3.1
loguru                0.5.3
matlabengineforpython R2021a
matplotlib            3.4.2
nidaqmx               0.5.7
numpy                 1.21.1
OpenNFT               1.0.0rc0
Pillow                8.3.1
pip                   21.2.1
pyHook                1.5.1
PyNIExp               0.27.1
pyparsing             2.4.7
PyQt5                 5.15.4
PyQt5-Qt5             5.15.2
PyQt5-sip             12.9.0
pyqtgraph             0.12.2
pyserial              3.5
python-dateutil       2.8.2
pywin32               301
scipy                 1.7.0
setuptools            57.4.0
six                   1.16.0
watchdog              2.1.3
wheel                 0.36.2
win32-setctime        1.0.3`

**Comment by tiborauer** [comment]
Does `python -m opennft` work for you?

**Comment by brainwatcher** [comment]
@tiborauer it works! Thank you!

**Comment by brainwatcher** [comment]
@ykoush I don't know why `pip list` not give a location list. Maybe I miss some accompanying argument.

**Comment by ykoush** [comment]
opennft_console also works for Win. We will update the documentation to close this issue.

**Comment by espdev** [comment]
Fixed in #121
