### ISSUE TITLE
Error about Protocol File setup.

### ISSUE THREAD

**Issue by brainwatcher** [OpenNFT/OpenNFT#122]
I am trying the `setup` step following the video tutorials. I set the `ini` and `json` files from `config` folders. The other directory are from downloaded `OpenNFT_DemoData` folder. But the `json` file seems could not be read correctly. The error in terminal is as below.  The ini file is `configs\NF_PSC_cont_155.ini`. The json file is `configs\NF_PSC_cont_155.json`. Could you give me some advices?

2021-07-29 10:54:46 | INFO      | opennft:setup - Setup application...
2021-07-29 10:54:46 | INFO      | opennft:actualize -   Actualizing:
2021-07-29 10:54:46 | INFO      | opennft:setup - memMapFile: C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\doc\OpenNFT_DemoData\NF_PSC\shared.dat
Brace indexing is not supported for variables of this type.

Error in loadJsonProtocol (line 34)
        protNames{x} = prt.ConditionIndex{x}.ConditionName;

Traceback (most recent call last):
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 1259, in setup
    self.loadJsonProtocol()
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 1840, in loadJsonProtocol
    self.eng.loadJsonProtocol(nargout=0)
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError:
  File C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\Lib\site-packages\opennft\matlab\utils\loadJsonProtocol.m, line 34, in loadJsonProtocol
![setupSnapShot](https://user-images.githubusercontent.com/33627072/127586842-d7a2314d-1b63-4428-9575-fb13a572c43e.png)

**Comment by tiborauer** [comment]
Your JSON seems to be `conn` rather than `cont`.

**Comment by ykoush** [comment]
Please carefully study Demo examples first, if Demo examples work, please post further questions under Discussions: https://github.com/OpenNFT/OpenNFT/discussions

**Comment by brainwatcher** [comment]
@tiborauer I am very sorry for the wrong figure. But the problem I asked is really existed. I had tested all the `NF_PSC_cont_155.json` and ` NF_PSC_conn_155.json`  protocal files. They gave the same errors. I think this is about some code in reading. I update my snapshot. 
@ykoush I am following the tutorials to use the Demo. If I have some further question beyond demo, I will ask in the Discussion part.

**Comment by ykoush** [comment]
Did you modify original Demo configs? If so, you can debug in Matlab to see what is causing the problem.

**Comment by brainwatcher** [comment]
@ykoush Yes, I did modify the `ini` file to modify the folder directories. The original directories are prefix by `__RT`, which is not the demo data directories in my own computer. Is these the forbidden or unrecommend modification? 
For the debug in MATLAB, I have another problem. When `Initial` finished, should it pop up a new MATLAB window as video tutorial? No new MATLAB window pop up in my computer after click `initial`. Is this meaning I have not set my `opennft`  with MATLAB right enough?

**Comment by TheAmid** [comment]
@brainwatcher to make MATLAB window pop up, you should modify following line on config.py

https://github.com/OpenNFT/OpenNFT/blob/caeea904a1214a0e2f3cd284e639e6a7429572bb/opennft/config.py#L29

and change `-nodesktop` to `-desktop`. After that it will be possible to debug MATLAB code.

**Comment by brainwatcher** [comment]
@TheAmid Thank you. I changed this option and successed in popping up a main MATLAB window. But I still could not setup well. To exclude the cause of my own modification of  `ini` file, I replace the `ini` file with the original one in Github. And then I copied the Demo data in the same directory as in the tutorials, which is like `C:\_RT\rtData\NF_PSC`. 
But it still gives the error in setup step with json file as below. The error is given in the python terminal, not in MATLAB. I debug in MATLB with the function `loadjson.m`.  It works well. So the error may come from `loadJsonProtocol` in Python part.  Could you give me some advice? The error message, setup window and MATLAB debug main window are as below.

**The error in python terminal.**
2021-08-01 08:14:54 | INFO      | opennft:setup - Setup application...
2021-08-01 08:14:54 | INFO      | opennft:actualize -   Actualizing:
2021-08-01 08:14:54 | INFO      | opennft:setup - memMapFile: C:\_RT\rtData\NF_PSC\shared.dat
Brace indexing is not supported for variables of this type.

Error in loadJsonProtocol (line 34)
        protNames{x} = prt.ConditionIndex{x}.ConditionName;

Traceback (most recent call last):
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 1259, in setup
    self.loadJsonProtocol()
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\opennft\opennft.py", line 1840, in loadJsonProtocol
    self.eng.loadJsonProtocol(nargout=0)
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError:
  File C:\Users\psylab706\Documents\MATLAB\ZW\openNFT\opennft-venv\Lib\site-packages\opennft\matlab\utils\loadJsonProtocol.m, line 34, in loadJsonProtocol
Brace indexing is not supported for variables of this type.

**The setup review parameter window.**
![opennftPython](https://user-images.githubusercontent.com/33627072/127770621-7c898155-a442-42b0-9338-54fd2dd13c6d.png)

**The "empty" MATLAB main window.**
![opennftMATLAB](https://user-images.githubusercontent.com/33627072/127770625-597af019-e999-4007-9e3a-09928ff60177.png)

**Comment by TheAmid** [comment]
@brainwatcher please, put breakpoint in main MATLAB window on this line

https://github.com/OpenNFT/OpenNFT/blob/caeea904a1214a0e2f3cd284e639e6a7429572bb/opennft/matlab/utils/loadJsonProtocol.m#L33

And show what is inside `prt` variable. It's a bit tricky, because I did the same check and got the same results (with loadjson). May be data inside `prt` will give us an answer.

**Comment by brainwatcher** [comment]
@TheAmid I am very happy for knowing how to debug in MATLAB of opennft! Imo, the error is because ` prt.ConditionIndex{x}`. The ` prt.ConditionIndex` is a struct, not a cell. So it should be ` prt.ConditionIndex(x)`. I found there are more than 1 errors with the same reason. Should I fix this by my own?

**Comment by brainwatcher** [comment]
@The Amid. Besides I found a problem in `loadJsonProtocal.m` line 76. The variable `x.ConditionName` is weird. I could not figure its meaning. This may be another problem.

**Comment by TheAmid** [comment]
@brainwatcher could you share your `NF_PSC_cont_155.json` file?
And what jsonlab version do you use?
It seems some problems with json-reader, because you have ConditionIndex as [1x1 array] and I have ConditionIndex as {[1x1 array]}, so something might be in the file. 

`x.ConditionName` is a part of lambda function, where `x` is an input variable.

**Comment by brainwatcher** [comment]
The `json` file's content is as below.  As for the `jsonlab`, my verison is 2.0. I think it should be the latest because I update it with git.  My MATLAB is 2021a. 

{
	"ContrastActivation": "+1*NFBREG",
	"SignalPreprocessingBasis": "NFBREG",
	"ConditionIndex": [
		{
			"ConditionName": "NFBREG",
			"OnOffsets": [
				[11,20],
				[31,40],
				[51,60],
				[71,80],
				[91,100],
				[111,120],
				[131,140]
			]
		}
	]
}

**Comment by TheAmid** [comment]
@brainwatcher thank you for this issue!

I found the root of this problem. I guess, you use jsonlab-master version, from jsonlab's GitHub. It seems jsonlab was partially updated and it caused the error, when after parsing `ConditionIndex` it becomes struct inside struct, but not cell-array inside struct.

I suggest to use official version from Mathworks website
https://www.mathworks.com/matlabcentral/fileexchange/33381-jsonlab-a-toolbox-to-encode-decode-json-files

**Comment by brainwatcher** [comment]
@TheAmid thank you for your answer. The jsonlab is the reason. The setup works well now.
