### ISSUE TITLE
Does OpenNFT support GE MRI scanner?

### ISSUE THREAD

**Issue by brainwatcher** [OpenNFT/OpenNFT#126]
Hi, I am trying to use the OpenNFT on a GE MRI scanner. But I found in the paper of OpenNFT, "An open-source Python/Matlab framework for real-time fMRI neurofeedback training based on activity, connectivity and multivariate pattern analysis", it said the software is currently compatible with Siemens and Philips MR scanner.  I found no relative information on the home page. Could you tell me can I use it on GE machine? Is there something special I should notice?

**Comment by ykoush** [comment]
Hi, we don't have a GE support at the moment. However, this shouldn't be difficult to implement and we could help you with this. You need to find out about data format and export properties of the GE scanner, and which functions could read them at Matlab and/or Python. The rest of the implementation is just about checking how .dcm for Siemens and .img/.hdr for Phillips are implemented in OpenNFT. Btw, the same concerns the newer Phillips .par/,rec data export format.

**Comment by brainwatcher** [comment]
Thank you for your reply! I am at the test phase on the GE scanner. I post this issue just to ensure my software choice.  If I have further questions, I would ask for more support. :)

**Comment by tiborauer** [comment]
Could we adapt [spm_parrec2nifti](https://github.com/spm/spm12/blob/master/spm_parrec2nifti.m) to handle par/rec?

**Comment by ykoush** [comment]
I think it first needs to be thoroughly checked, including timings, etc. The same concerns par/rec for Phillips. I know some people tried it for rt.

**Comment by tiborauer** [comment]
Do you mean others have already tried this function for rt and it did not perform well?

**Comment by Metasoliton** [comment]
Hi Tibo,

With regards to the Phillips Par/Rec work, I have written the following two Matlab functions that may serve a reasonable starting point:

1) https://github.com/rtQC-group/rtQC/blob/master/api-matlab/rtQC_xtc2nii.m

2) https://github.com/rtQC-group/rtQC/blob/master/api-matlab/rtQC_xtc_QA.m

As you can see there, the files have more comments than code, so I hope it is well-explained. It basically provides my tried and tested workflow when dealing with par/rec, but note that was tested with the XTC module (not DRIN). Have a look and if there is something you would like to discuss, I would be happy to do that here or jump in a call.

**Comment by ykoush** [comment]
This could be checked first, and once verified, could be implemented in OpenNFT.

**Comment by tiborauer** [comment]
I have not tried it because we do not have a GE scanner. @brainwatcher may be able to tell.
