### ISSUE TITLE
What script should I install on the MRI scanner machine?

### ISSUE THREAD

**Issue by brainwatcher** [OpenNFT/OpenNFT#127]
Hi, I am trying to test the openNFT on a GE machine.  The collection of MRI data and visual stimulus are on different computers. So I think I should install some python scripts to send the raw volume data through TCP/IP. Which script should I install on the MRI data collection computer? Its function may be to send the raw volume in every interval of TR.  By now, I test the openNFT runs well on the visual stimulus computer. But I think something on the collection computer is necessary? Is there any way I could get an example script of it? 
This issue may be silly cause my misunderstood of how rtFMRI runs If so, please tell me.
Thank you.

**Comment by brainwatcher** [comment]
I think I misunderstood the mechanism of TCP/IP. I need to install nothing on the collection computer. I just need to find the IP address and the volume file type.

**Comment by ykoush** [comment]
There could be a soft for TCP/IP, e.g. if you are operating between Linux and Win, not necessarily in Python, e.g. http://www.labf.com/nfsaxe/. 
The basic rt export is about a proper data sharing (IP, shared folder) and proper rt data export (configuration, data format).

**Comment by tiborauer** [comment]
@brainwatcher, there seems to be some confusion. TCP is for (real-time) data export, while UDP is for sending feedback (and conditions) to visualisation over network.

The data over TCP/IP has been developped and tested on Siemens systems only and requires a functor and a script written and compiled by Michael Lührs in Maastricht. I am afraid I have no experience with NFT on GE systems 

The UDP requires no extra script, however, your visualisation must be able to handle data over UDP. The [corresponding test script](https://github.com/OpenNFT/OpenNFT/blob/master/tests/testUDPReceiver.py) can be used as an example.
