### ISSUE TITLE
Checks on plugins' installation and operation.

### ISSUE THREAD

**Issue by ykoush** [OpenNFT/OpenNFT#146]
@tiborauer could you please make sure that all site packages and plugins are properly taken using recommended installation via PyCharm (https://opennft.readthedocs.io/en/latest/install_pycharm.html) and check that they are all operational. We had quite many updates in the main project that could potentially affect them. Please keep in mind that current WIP is to make the core Python processes more parallel, which may require one more check in the nearest future, after corresponding PRs.

**Comment by tiborauer** [comment]
Sure! Does it have to be PyCharm? I use Viscose and never used PyCharm

**Comment by tiborauer** [comment]
I have revised all three plugins and submitted #149 to adjust them.

**Comment by ykoush** [comment]
#149 closed it.
