### ISSUE TITLE
Potential new Installation Issue related to setup of Matlab Engine for Python

### ISSUE THREAD

**Issue by ykoush** [OpenNFT/OpenNFT#152]
We recently encountered earlier unobserved Issue with our automatic Installation. Despite all commands run without warning and errors, the Matlab engine is not set. Run the following command to setup the Matlab engine in Pycharm terminal under VENV (set your paths):
`cd "c:\Program Files\MATLAB\R2020b\extern\engines\python"
python setup.py build --build-base="c:\OpenNFT\OpenNFT_venv\Lib\site-packages\MatlabEngineBuild" install`
We are observing if this issue repeats with more users.

**Comment by tiborauer** [comment]
I also experienced the same issue.

**Comment by ykoush** [comment]
So strange, but looks reproducible and could be redirected to @espdev

**Comment by ladigu** [comment]
I have a similar problem on my Mac: After installing OpenNFT 'matlabengineforpython' is not listed. tiborauer's suggestion didn't work. Is there a solution for the installation on Mac? Thank you in advance!

**Comment by ykoush** [comment]
Did you try my solution?
