### ISSUE TITLE
Improve documentation for jsonlab install

### ISSUE THREAD

**Issue by smweis** [OpenNFT/OpenNFT#154]
We experienced issues running demos because the json-lab link points to the github page for jsonlab-master rather than File exchange. Uninstalling jsonlab-master and installing jsonlab-2.0 fixed the issue we were having (https://github.com/OpenNFT/OpenNFT/issues/122) which has been closed.

**Comment by ykoush** [comment]
@TheAmid I see, I think we can do so, or update addressing the json structure according to their master version, correct?
