### ISSUE TITLE
OpenNFT not reading .nii.gz files

### ISSUE THREAD

**Issue by aavenka** [OpenNFT/OpenNFT#157]
Hi,

I am having .nii.gz streamed to OpenNFT, I have it set to read IMAPH files; however, it throws an error "list index out of range" in opennft.py on line 758. I think it's an issue reading in the filename, which I have coming in as "img-00001.nii.gz". Do you have any advice on how to fix this error?

**Comment by ykoush** [comment]
Well, this is not supposed to work with this format, I wonder how did you get it? What is your scanner model and year?
Is it the only rt export option? How the gz occurs, is it necessary?
I could only suggest that you need to extract the .gz first, or use alternative MATLAB or Python way to read it (pyOpenNFT is Private as for now, but could be put Public soon - it is entirely in Python). I'd check the file somewhere outside openNFT for header information, orientation, etc. So if you need to figure out entirely your own way to operate with such inputs, it is possible, and could be guided based on .dcm or .img (with separate .hdr example). Btw, switching just to IMAPH won't help, it was programmed for another case, rather old Phillips setup, like Achieva.

**Comment by aavenka** [comment]
We have a special sequence on the Siemens scanner that streams the files to a connected computer during fMRI acquisition, and these files are saved as .nii.gz (this is the script it uses: https://github.com/gablab/murfi2/blob/master/util/python/receive_vsend/receive_nii.py). It was working with an older version of OpenNFT but now does not work with .nii.gz files

**Comment by ykoush** [comment]
Not yet, you are first who ask for this here. I think we could easy extend (py)OpenNFT for it. Are you confident doing it yourself, or need some introduction/help to the code. I'd suggest that you schedule a zoom with @TheAmid, just send a brief email to opennft@gmail.com.

**Comment by ykoush** [comment]
As I wrote in #156, repeating this idea here. @aavenka should find out  how the github code they use (this is the script it uses: https://github.com/gablab/murfi2/blob/master/util/python/receive_vsend/receive_nii.py) produces .gz on a Siemens PC side. The easiest could be that @aavenka checks that .gz could be disabled there. Please try to find out and let us know.

**Comment by pwighton** [comment]
Hi, author of vsend here.  The data comes off the scanner uncompressed, in what @satra and I call the "openheader" format.  The goal was to make a data format that could be implemented across all major scanner manufacturers, but to my knowledge, there is only the Siemens implementation so far.

It's the `receive_nii.py` script that is compressing the data before writing it to disk. 
 @aavenka, can you try editing your copy of `receive_nii.py` and remove the `.gz` extension from the filestrings on lines 157 and 160?  That should be enough to get it to save uncompressed images.

Note that `receive_nii.py` was never intended to be part of a real-time processing pipeline. 
 Writing to disk will induce some unwanted latency in the processing pipeline and I would encourage you to consider creating a pipeline where intermediate data never touches a filesystem, but this should be fine if you just want to test to see if it will work.
