### ISSUE TITLE
DICOM read error

### ISSUE THREAD

**Issue by ngs5** [OpenNFT/OpenNFT#163]
Hi,

Since the new scanner update using the new DICOM export format, we occasionally get the error illustrated in the attached screenshot.

However, the exported files are readable and do not differ from previous NF runs...

...has anyone encountered such an error before? I am not (yet) seeing the underlying issue.

This happens from time to time after one or two NF runs, and we have to restart the whole PyCharm + OpenNFT processes to make it work again.

Thanks for any suggestions,

Best,
Nicolas
![issue copy](https://github.com/OpenNFT/OpenNFT/assets/48179079/35fbcf03-2fd1-4893-a5f2-d1cad2f2e666)

**Comment by ykoush** [comment]
Hi Nicolas,
when this happens, at a first file, or random files? 
Also, whether the file itself, in a short while, has no pbm to open with the same function (essentially Matlab's one, which works on other files, meaning the export imperfection beyond the programmed checks so far)?
If the answer is yes to both of them, I could suggest that the file is not entirely written by the scanner somehow, also we have a check for that. 
The restart of the entire soft probably is note necessary, I'd let the scanner go a bit, and restart exact the same series in opennft, perhaps it runs without problems. Or, run the entire series offline, after copy, to ensure that there is no pbm anymore.  Let me know.

**Comment by ngs5** [comment]
Hi Yury,
It happens at first file, and the file is perfectly read by MATLAB's dicomread offline (i.e., just tried now).
However, this seems to happen after one NF run has been carried out (i.e., at the beginning of Run2), if I do not re-initialize OpenNFT beforehand, so I am not really understanding why...
The scanner part is also unclear because otherwise it would also happen at Run1... but it never did so far.

**Comment by ykoush** [comment]
Do you mean that you can reproduce the problem between runs using offline export simulation, via copy function that we have? That would be great to fix.
Re-initialization perhaps does some more cleaning of variables, I wonder when did you download it last. In GitHub, you could check how far is your local version form master. If I remember well, there were a few cleanings done by @TheAmid between the sessions.
