### ISSUE TITLE
Transfer DICOM data

### ISSUE THREAD

**Issue by yiweili07** [OpenNFT/OpenNFT#165]
Our fMRI equipment (manufactured by Siemens) is currently unable to send DICOM data in real-time to another computer for analysis. Could you please offer guidance or suggest potential solutions to help me overcome this obstacle?

**Comment by ykoush** [comment]
You have to check first if you computer is seen by a scanner via LAN, usually, a question to IT support who set it up on a network.
Then, under admin pass for your local scanner edit ideacmdtool given you carefully check the things when you change these options, ie know what you are changing, local rtPC is mapped to x:\ on the MR console PC. These changes are typically reset after re-opening the user card.
ideacmdtool 4 1 -1
ideacmdtool 4 2 localhost
ideacmdtool 4 3 x:\
ideacmdtool 5 8 1

There are some other ways, but this is to check the things.
