### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#35]
As we add more and more new functions and modifications developed in different labs, it becomes more and more important to test PR independently and parallel. I suggest accepting PRs only if all examples have been tested in at least two places.

**Comment by da0c** [comment]
Usually, we test PR in different environments, e.g. in Yuriy's lab and in my or Eugene's. 
M.b. good idea write comments on PR if it was successfully tested in smbd. environment, so, we could merge PR only if it has more then two success.

More convenient practice is to setup a build server with CI and testing ... it is significantly more complicated, but perhaps it will become necessary in the near future.
