### ISSUE TITLE
Is Brew Install Available? 

### ISSUE THREAD

**Issue by pacarvalho** [OpenNFT/OpenNFT#36]
I am a Mac user and it is very common and convenient to be able to install packages via a package manager such as _Brew_. 

Has there been work done towards this purpose? If not, would there be interest in making this software installable via _Brew_? I haven't tried creating a _Brew_ package before but I could give it a try in a PR. 

I am about to try installing this software for the first time now.

**Comment by ykoush** [comment]
I don't think anyone tried it via Brew here, please give it a try if you could. Thank you.

**Comment by pacarvalho** [comment]
I will take a look into how it would work! :)

I did run into some problems installing on my MacOS 10.14.5. Related to PyQT not being able to install if I pass the `--matlab-root=<MATLABROOT>` command which somehow were resolved by **not** passing it that flag...
