### ISSUE TITLE
displayImage invalid entry in index array (OpenNFT.py line 1565)

### ISSUE THREAD

**Issue by lydiatgit** [OpenNFT/OpenNFT#4]
OpenNFT crashes in OpenNFT.py line 1565 in displayImage with an invalid entry in index array. 

This happens in online and offline mode always at the same point of time. 

![errormessage_20180810_opennft_line1565](https://user-images.githubusercontent.com/453067/43972888-20751462-9cd6-11e8-9dc3-ae31c3b68e49.png)

**Comment by da0c** [comment]
It seems to be another problem in iGLM computation.
Please provide me a link to the data and setting files, caused this error, and I try to reproduce it.
You could place the link here or send it to me privatelly to artniko@gmail.com.

**Comment by lydiatgit** [comment]
Hey Artem,

I've added you to the dropbox folder containing the data and our config
files.
Please let me know if you didn't receive any dropbox notification.

And many thanks for your help.

Best regards,
Lydia

-----------------------------------------------------------------------------------------
Dr. rer. nat. Lydia Hellrung, Dipl.-Inf.
University of Zurich
Department of Economics
Blümlisaplstraße 10
8006 Zurich, Switzerland
phone: + 41 (0) 44 634 4838

e-mail: lydia.hellrung@econ.uzh.ch
-----------------------------------------------------------------------------------------



Von:	"Artem Nikonorov" <notifications@github.com>
An:	"OpenNFT/OpenNFT" <OpenNFT@noreply.github.com>
Kopie:	"lydiatgit" <lydia.hellrung@uzh.ch>, "Author"
            <author@noreply.github.com>
Datum:	13/08/2018 12:16
Betreff:	Re: [OpenNFT/OpenNFT] displayImage invalid entry in index array
            (OpenNFT.py line 1565) (#4)



It seems to be another problem in iGLM computation.
Please provide me a link to the data and setting files, caused this error,
and I try to reproduce it.
You could place the link here or send it to me privatelly to
artniko@gmail.com.

**Comment by da0c** [comment]
Hi,
it's all right, I've recivied files from dropbox. So, I will try to reproduce and fix your problem.
Thank you for testing OpenNFT in your case)))

Best regards,
Artem

**Comment by da0c** [comment]
I also need .ini file and .json with protocol.

**Comment by lydiatgit** [comment]
Sorry, you're right, I thought they were in nfb.zip, but apparently they
decided to jump out of it :-), sorry, here they are.

One short comment: In the setupProcParams.m of the toolbox, we changed the
tContr in our condition like this according to SPM.mat:

if isPSC && strcmp(P.Prot, 'Cont') && fIMAPH
    tmpSpmDesign = SPM.xX.X(1:P.NrOfVolumes-P.nrSkipVol,1);
    % this contrast does not count constant term
    %mainLoopData.tContr = [1];
    mainLoopData.tContr = [0; 1];
end


Thanks a lot
Lydia



(See attached file: NF_PSC_cont_MT.json)(See attached file:
NF_PSC_cont_QA_SNS_MT.ini)(See attached file: SPM_PSC_Cont_MT.mat)





Von:	"Artem Nikonorov" <notifications@github.com>
An:	"OpenNFT/OpenNFT" <OpenNFT@noreply.github.com>
Kopie:	"lydiatgit" <lydia.hellrung@uzh.ch>, "Author"
            <author@noreply.github.com>
Datum:	13/08/2018 17:06
Betreff:	Re: [OpenNFT/OpenNFT] displayImage invalid entry in index array
            (OpenNFT.py line 1565) (#4)



I also need .ini file and .json with protocol.

**Comment by da0c** [comment]
Dear Lydia, unfortunatelly, there are no attached files if you reply on GitHub messages.
So, I propose to use conventional email for this data exchange and conversation.
Just send me email from your address.

**Comment by da0c** [comment]
The problem was just on bounding poins of stat map.
The cause probably placed in indexing diffrence (1-based and 0-based) between matlab and python. 
I'll apply fast fix - just make these points of stat map zero-valued.

**Comment by lydiatgit** [comment]
That sounds great!
I just can check at the end of the week, but I'll let you know about the
results then.

Many many thanks for your help
Lydia







Von:	"Artem Nikonorov" <notifications@github.com>
An:	"OpenNFT/OpenNFT" <OpenNFT@noreply.github.com>
Kopie:	"lydiatgit" <lydia.hellrung@uzh.ch>, "Author"
            <author@noreply.github.com>
Datum:	21/08/2018 11:10
Betreff:	Re: [OpenNFT/OpenNFT] displayImage invalid entry in index array
            (OpenNFT.py line 1565) (#4)



The problem was just on bounding poins of stat map.
The cause probably placed in indexing diffrence (1-based and 0-based)
between matlab and python.
I'll apply fast fix - just make these points of stat map zero-valued.

**Comment by da0c** [comment]
Indexing difference between matlab and python is the real cause of the bug.
So I provide right fix for it.

**Comment by ykoush** [comment]
This recent closure fixes this old issue in more elegant fashion, since I recently was able to caught this very rare data-driven bug one more time.
