### ISSUE TITLE
No PTB display in DCM

### ISSUE THREAD

**Issue by NinaWie** [OpenNFT/OpenNFT#41]
After running into problems in our DCM paradigm, we tested if with your demo data and config files and it did not work either. The problem is that only the first screen shows up (the fix point), but then no other stimuli ("REST" and "MOVE"). The error seems to be that in the mainLoop in opennft.py, the displaying function in ptbscreen.py is never called. This occurs because in the part starting from Line 615, https://github.com/OpenNFT/OpenNFT/blob/d8dbfac7c16aa8d0e7196efd3c8f8fac047e5e58/opennft/opennft.py#L615-L633

We see that displayScreen() is only called for DCM if the protocol is "Inter". However, in our paradigm as well as in our experiment, DCM is used with "InterBlock. (https://github.com/OpenNFT/OpenNFT/blob/d8dbfac7c16aa8d0e7196efd3c8f8fac047e5e58/opennft/configs/NF_DCM_1060.ini#L26. 

I would expect that you get the same issue when testing the DCM example. A fix would be quite simple, by putting the elif "DCM" one level higher for example. 

It would be great if you could fix that. Thanks!

**Comment by da0c** [comment]
Will check

**Comment by da0c** [comment]
I think, that
`if self.P['Prot'] == 'Inter' or self.P['Prot'] == 'InterBlock':`
is the right condition for this, fixed.
