### ISSUE TITLE
Putative bug in `preprVol`

### ISSUE THREAD

**Issue by moritz-gruber** [OpenNFT/OpenNFT#47]
I have a quick question about a putative bug we came across recently (see attached screenshot).

In `preprVol` in the section `%% sharing iGLM results`, you find the non-zero elements and shift them by 1 on line 360. 

```posIdx2D = find(statMap_2D > 0) - 1;```

However, you retrieve the activation values based on those *shifted indices* rather than the indices returned by the find call on line 363. 

```tmpStrData = matData2strData(statMap_2D(posIdx2D)*255);```

If the activations at those shifted indices are zero, ‘matData2strData’ returns a string of semicolons (rather than a string of zeros separated by semicolons), which results in a shape mismatch between the indices and their corresponding activations (empty np.array) in python (specifically l. 1690 `opennft.displayImage()`):  

My question to you is therefore whether I missed how index-shift on line 360 has purposes beyond accounting for python's zero-indexing or whether one could simply shift back by modifying line 363 as follows:    

```tmpStrData = matData2strData(statMap_2D(posIdx2D + 1)*255);```

Thanks in advance for your help.

![image](https://user-images.githubusercontent.com/51325123/60351624-765ea800-99c6-11e9-91ab-622f06ae5e1f.png)

**Comment by ykoush** [comment]
Actually the most recent code version contains the fix already, seems very similar you offered, this was #4: f7f313c976bb4e1f859b62f918b0e44589693280

Could you please check if it works for you.
