### ISSUE TITLE
Matlab Internal Engine Error

### ISSUE THREAD

**Issue by aavenka** [OpenNFT/OpenNFT#48]
Hi all,

I am installing OpenNFT on a Windows 10 machine through Python 3.5. After everything is compiled, I run "opennft_console" and it opens, when I click "initialize", matlab opens and closes and the console freezes. The command prompt gives an error: "Error using import. Import argument 'matlab.internal.engine.input' cannot be found or cannot be imported." Does anyone know how to solve this?

Thanks in advance!

Arun

**Comment by espdev** [comment]
@aavenka could you show full exception traceback and error text from console?

**Comment by aavenka** [comment]
Attached is the command prompt output to the error.
![error](https://user-images.githubusercontent.com/45500866/60548614-82ad7280-9cf0-11e9-9a14-f7a4f1670dd2.PNG)

**Comment by espdev** [comment]
@aavenka 

What Matlab version do you use?

And could you please print `startup_options` variable from file `mlproc.py` line 152?
https://github.com/OpenNFT/OpenNFT/blob/990c4727b4fba0ccb079ea0d0f49b9270bad48d2/opennft/mlproc.py#L152

**Comment by aavenka** [comment]
I am using Matlab R2018a, I'm unsure how to print that variable, I added print(start_options) to the file mlproc.py after that line in the OpenNFT_venv/Lib/site_packages/opennft. However, when I open opennft_console, it does not print out anything after I click initialize. I'm not sure where startup_options is being defined. What would be the easiest way to print that variable?

**Comment by espdev** [comment]
Please add `print('STARTUP OPTIONS:', startup_options)` line before `me.start_matlab(startup_options)` line

**Comment by aavenka** [comment]
It prints out STARTUP OPTIONS: -desktop

**Comment by espdev** [comment]
It looks as correct startup_options string. I do not know what is happening. Please try to reinstall opennft package:

```
c:\users\dfeder\opennft\opennft_venv\Scripts\pip install -U --force-reinstall git+https://github.com/OpenNFT/OpenNFT.git
```

**Comment by ykoush** [comment]
May be it could help to have Python 3.6 instead of 3.5 in your setup.

**Comment by aavenka** [comment]
I tried re-installing at it didn't work (same error), here is the log file from the installation. [ouput.txt](https://github.com/OpenNFT/OpenNFT/files/3370237/ouput.txt)

**Comment by espdev** [comment]
@aavenka Thanks for the output file. Unfortunately, your `output.txt` file does not contain some important information about installation process and events.

Could you please try to use the following command:
```
c:\users\dfeder\opennft\opennft_venv\Scripts\pip install -v -U --force-reinstall git+https://github.com/OpenNFT/OpenNFT.git --log install.log
```

And show `install.log` file.
Thank you!

**Comment by aavenka** [comment]
Attached is the install.log

Thanks!
[install.log](https://github.com/OpenNFT/OpenNFT/files/3403627/install.log)

**Comment by aavenka** [comment]
Hey guys, I fixed the problem by reinstalling through conda instead of python, everything works now!

**Comment by ykoush** [comment]
Great, surprising, though!
