### ISSUE TITLE
Using Nifti Data

### ISSUE THREAD

**Issue by aavenka** [OpenNFT/OpenNFT#49]
Hi all,

I have set up Open NFT and I am having an issue, the scanner files are being sent in a dicom format to the computer with Open NFT, but there is an issue from there analyzing the data because the header is different from dicom. Is there any way to easily use NIFTI data?

Thanks,
Arun

**Comment by tiborauer** [comment]
What scanner do you use? It seems non-Siemens to me. I think @ykoush has more experince with them.

**Comment by aavenka** [comment]
We do use a Siemens Prisma scanner, but we have a code that retrieves the images in real time and saves it as a Nifti.

**Comment by tiborauer** [comment]
I see. I think the IMAPH datatype should do the trick, because it also expects NIfTI data (see https://github.com/OpenNFT/OpenNFT/blob/5e5e6b99d1d2ee4473254214b82b2b817765d86d/opennft/matlab/nfbPreprVol/preprVol.m#L101-L108).

**Comment by aavenka** [comment]
Do I just need to change the expected file type on GUI to IMAPH, and keep the file ending as .nii.gz in the expected file name?

**Comment by tiborauer** [comment]
I would start with that. spm_vol can handle .nii.gz.

**Comment by aavenka** [comment]
It worked, thanks! I'm just having an issue now with an error (attached). I can change the vector manually to match the size of the "invNn", but I'm not sure if this is changing the calculations.
![error_opennft](https://user-images.githubusercontent.com/45500866/62978360-16de1f80-bdef-11e9-8026-0d7b60cb3806.PNG)

**Comment by tiborauer** [comment]
The contrast vector must be a column vector.

**Comment by aavenka** [comment]
It's a 10x1 column vector, but the invNn is a 12x12 matrix, so they won't multiply.

**Comment by tiborauer** [comment]
How did you specify your contrast vector? Do you know what are the 12 columns in the design?
OpenNFT should automatically append 0s for the 6 moco parameter and for the constant (I assume), so it seems you have 5 regressors-of-interest, but only 3 contrast weights.

**Comment by aavenka** [comment]
Which file defines the regressors?

**Comment by tiborauer** [comment]
Your JSON-file describing the conditions.

**Comment by aavenka** [comment]
Thanks, got it to work!
