### ISSUE TITLE
OpenNFT PTB crashes on some screen resolutions

### ISSUE THREAD

**Issue by lydiatgit** [OpenNFT/OpenNFT#5]
Using a screen with 1024x768 screen resolution led to a crash of PTB display in file displayFeedback.m when using Fullscreen mode. 

The display is using fractions of the screen resolution, such as P.Screen.w/2-P.Screen.h/4, which might cause a problem of uneven numbers. Introducing rounding by floor(...) solved the issue for our purpose here, but has  to be introduced overall the display functions. 
So, here I changed the Matlab code as follows for a PSC feedback type, which solved the issue for the purpose here:

switch feedbackType
    %% Continuous PSC
    case 'bar_count'
        dispValue  = dispValue*(floor(P.Screen.h/2)-floor(P.Screen.h/10))/100;
        switch condition
            case 1 % Baseline
                % Text "COUNT"
                Screen('TextSize', P.Screen.wPtr , floor(P.Screen.h/10));
                Screen('DrawText', P.Screen.wPtr, 'REST', ...
                    floor(P.Screen.w/2-P.Screen.h/4), ...
                    floor(P.Screen.h-P.Screen.h/5), instrColor);
                % Fixation Point
                Screen('FillOval', P.Screen.wPtr, [255 255 255], ...
                    [floor(P.Screen.w/2-P.Screen.w/200), ...
                    floor(P.Screen.h/2-P.Screen.w/200), ...
                    floor(P.Screen.w/2+P.Screen.w/200), ...
                    floor(P.Screen.h/2+P.Screen.w/200)]);
                % draw target bar
                Screen('DrawLines', P.Screen.wPtr, ...
                    [floor(P.Screen.w/2-P.Screen.w/20), ...
                    floor(P.Screen.w/2+P.Screen.w/20); ...
                    floor(P.Screen.h/10), floor(P.Screen.h/10)], ...
                    P.Screen.lw, [0 255 0]);
                % draw activity bar
                Screen('DrawLines', P.Screen.wPtr, ...
                    [floor(P.Screen.w/2-P.Screen.w/20), ...
                    floor(P.Screen.w/2+P.Screen.w/20); ...
                    floor(P.Screen.h/2)-dispValue, ...
                    floor(P.Screen.h/2)-dispValue], P.Screen.lw, [0 255 0]);
            case 2 % Regulation
                % Fixation Point
                Screen('FillOval', P.Screen.wPtr, [255 255 255], ...
                    [floor(P.Screen.w/2-P.Screen.w/200), ...
                    floor(P.Screen.h/2-P.Screen.w/200), ...
                    floor(P.Screen.w/2+P.Screen.w/200), ...
                    floor(P.Screen.h/2+P.Screen.w/200)]);
                % draw target bar
                Screen('DrawLines', P.Screen.wPtr, ...
                    [floor(P.Screen.w/2-P.Screen.w/20), ...
                    floor(P.Screen.w/2+P.Screen.w/20); ...
                    floor(P.Screen.h/10), floor(P.Screen.h/10)], ...
                    P.Screen.lw, [0 255 0]);
                % draw activity bar
                Screen('DrawLines', P.Screen.wPtr, ...
                    [floor(P.Screen.w/2-P.Screen.w/20), ...
                    floor(P.Screen.w/2+P.Screen.w/20); ...
                    floor(P.Screen.h/2)-dispValue, ...
                    floor(P.Screen.h/2)-dispValue], P.Screen.lw, [0 255 0]);
                Screen('TextSize', P.Screen.wPtr , floor(P.Screen.h/10));
                Screen('DrawText', P.Screen.wPtr, 'MOVE FINGER', ...
                    floor(P.Screen.w/2-P.Screen.h/4), ...
                    floor(P.Screen.h-P.Screen.h/5), instrColor);
        end
        P.Screen.vbl = Screen('Flip', P.Screen.wPtr, ...
            P.Screen.vbl + P.Screen.ifi/2);
        
        %% Intermittent PSC
    case 'value_fixation'

**Comment by da0c** [comment]
I've included proposed floor-ing for the screen coordinates in displayFeedback.m.
It seems to be our first pull-request, thank you!
