### ISSUE TITLE
Optional MATLAB engines

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#53]
These MATLAB engines are used only for selected use cases:
- mlModelHelper (DCM model computation)
- mlPtbDcmHelper (PTB display and DCM model computation if mlModelHelper is not in use)

I wonder whether we could make their launch optional to reduce CPU and memory load, as well as initialization and finalization times.

EDIT: mlModelHelper is already optional (see config.USE_MATLAB_MODEL_HELPER); however, we could make this setting (and that for mlPtbDcmHelper) dependent from parameters (i.e. `P['Type']`/`str(self.cbType.currentText())` and `config.USE_PTB`/`self.cbUsePTB.isChecked()`) rather than config settings. It also means that reviewing parameters should be enabled before initialization.

**Comment by da0c** [comment]
Originally, it was optional due to config settings, I will revise.

**Comment by da0c** [comment]
I added DISABLE_PTB flag in config.py.
If this flag is True, PTB Matlab helper doesn't start on run_matlab.
Please, check.
