### ISSUE TITLE
Definition of initLim

### ISSUE THREAD

**Issue by NinaWie** [OpenNFT/OpenNFT#54]
Hi, we noticed that in scaleTimeSeries a threshold variable initLim is used, which defines the initial maximum for scaling (and -initLim defines the initial minimum). We looked up how it is computed, and found that it is defined as 0.005*mean(rawTimeSeries) as seen here:

https://github.com/OpenNFT/OpenNFT/blob/990c4727b4fba0ccb079ea0d0f49b9270bad48d2/opennft/matlab/nfbPreprSig/preprSig.m#L144 

Now we wondered if there is any particular reason for that definition? The absolute values of rawTimeSeries can be very diverse, can't they? So how is it guranteed that this computation yields a useful initial minimum or maximum? Would be great if you could explain it more in detail, maybe there is something we overlooked. Thanks!

**Comment by ykoush** [comment]
This is just an initial threshold. You can see how it works from the scaling procedure at the middle and low panel plots. The threshold (e.g., .5% or 1%) is pretty much arbitrary and is based on your expectation about BOLD amplitude during the first regulation block and later on. Pilots with the same task could help to identify this value by getting some ideas about expected PSC values. The threshold or defined max/min values are used to set the scaling limits as soon as activity grows as set in logic of scaleTimeSeries.m. Overall, this is just an implemented scaling methods which are many.
