### ISSUE TITLE
Sending condition labels via UDP is disrupted 

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#56]
I am afraid I have just checked upon this commit of 234996f, which prevent presenting instructions and sending condition labels for continuous NFT. Is that also an intended behaviour?

I am happy to correct it - revert it, essentially; but I want to avoid making circles.

**Comment by ykoush** [comment]
If I remember well, we found it as a repetition of place at https://github.com/OpenNFT/OpenNFT/blob/d6de8edd87ad20a79dac2a627a768fa0bb9ec560/opennft/opennft.py#L643. Could you please check why this remaining part is not working for you?

**Comment by tiborauer** [comment]
@ykoush, Whom are you asking?

If me, then I do not refer to SVM but PSC and refer to the line https://github.com/OpenNFT/OpenNFT/blob/d6de8edd87ad20a79dac2a627a768fa0bb9ec560/opennft/opennft.py#L636, which is executed only if `(self.P['Prot'] == 'Inter' or self.P['Prot'] == 'InterBlock') and self.P['Type'] == 'PSC'`, i.e. Inter and InterBlock PSC.

**Comment by ykoush** [comment]
Yes. If I understand properly now, we are basically talking about adding one more case to send UDP instructions for continuous PSC. If so, I don't think we need to revert our previous commit. Please add this case that works for you via a small PR. Thank you.

**Comment by tiborauer** [comment]
See #57
