### ISSUE TITLE
handling non-sequential data export 

### ISSUE THREAD

**Issue by Apurva674** [OpenNFT/OpenNFT#58]
openNFT gets stuck waiting for file that already arrived, eventually non-sequentially exported

**Comment by da0c** [comment]
in progress

**Comment by da0c** [comment]
I closed it, but the control flow still needs to be refactored a bit.
Please, check it.

**Comment by Apurva674** [comment]
Hi, could you please let me know if the #58 problem is fixed in the latest version? I have still been using the older version and it seems to occur randomly.

**Comment by ykoush** [comment]
Yes, we did some refactoring and tests - as you may see from @da0c comment above - and where waiting for a test on your side. We have to reproduce the error if it is still there. The best thing to do is just get the new version of the soft, install it under a separate VENV environment and run a good number of like 15-20 min phantom runs on it to see the problem a few times. You don't need to do anything to your current setup until you fix/check the new setup. The very quick installation guide is here on a README - https://github.com/OpenNFT/OpenNFT.
We also were waiting for your diagnostics of periodicity of file appearances in your folder. This could be done under proper monitoring on when the files where sent to the folder, and if there are some inconsequential file appearances on rtPC. Just make sure that you get this file information available on your rtPC OS.

**Comment by Apurva674** [comment]
Alright, I will try the new version. Unfortunately, our rtPC doesn't display time in milisecs so its difficult to say the accurate time of appearance of every file. Is there any other way to do that?

**Comment by ykoush** [comment]
You have to try to search around 'Get creation time of file in milliseconds' for your OS and hard drive.

**Comment by Apurva674** [comment]
I have installed the newest version and tried to run my protocol. I had following error with "FirstFileName". 
![error](https://user-images.githubusercontent.com/58774179/84148675-9d8b7980-aa5f-11ea-9aac-6414eb807a51.jpg)

**Comment by da0c** [comment]
Looks strange. Probably, it is a problem with your project parameters. Please, provide a screenshot with your settings pane.

**Comment by ykoush** [comment]
You also have to use updated .ini and .json files. Please check, or use a template those at \opennft\configs
Also, you may quickly find out in debug mode when setting a break point there. Most likely this parameter for some reason is not set, or there is a conflict around first file name rooting in your setup. Btw, may be somebody already installed the newest version at your scanner rtPC..
