### ISSUE TITLE
Undefined function 'logsig'

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#68]
https://github.com/opennft/OpenNFT/blob/1c01c1fdd34f6db35fb8081d3add0a3bdaaabc62/opennft/matlab/nfbPreprSig/preprSig.m#L372

The function seems to be part of the Deep Learning Toolbox (https://uk.mathworks.com/help/deeplearning/ref/logsig.html). Shall we add it to the requirements?

**Comment by espdev** [comment]
I think we could just use `a = 1 ./ (1 + exp(-zcoredVal(end)));`

**Comment by da0c** [comment]
logsig is implemented in neural net toolbox, and implemented as shown by @espdev 
So I agree with @espdev

**Comment by tiborauer** [comment]
I am about to submit a PR about optional implicit baseline. Shall I add it?

**Comment by da0c** [comment]
I fix it by direct commit))
