### ISSUE TITLE
About Online mode

### ISSUE THREAD

**Issue by ptailyyy** [OpenNFT/OpenNFT#7]
For the demo data, when I use the Offline mode it worked very well, but if I unchecked the Offline mode, and send the same DCM file to the watch folder in every 2 seconds, the OpenNFT software did not worked, likely did not receive the data ( in the Review Parameters page displayed "MRI Watch Folder exists. First file does not exist." ), and no errors exported. I was wondering if you could provide some more details or methods to solve this problem.  Thank you for your time.

**Comment by da0c** [comment]
If I correctlly understand, your comment refers to the issue #1 , so, please place your comment there and reopen it. It is better to keep all related dicussion in one issue.
Thank you!

And anyway we will check the online mode case.

**Comment by ptailyyy** [comment]
OK, I have commented refers to issue #1, but I cannot reopen it.

**Comment by da0c** [comment]
Ok, I've reopened #1
