### ISSUE TITLE
key timings for Python 3.6 and Matlab 2019b on Win 10

### ISSUE THREAD

**Issue by ykoush** [OpenNFT/OpenNFT#70]
Upon some user requests, we provide the check of timings for Matlab 2019b using a few Demo feedback and no feedback data. An independent check, but comparable to Koush et al. 2017 Neuroimage Table 3. @TheAmid will comment with details.

**Comment by tiborauer** [comment]
Do you use the same release and hardware?

**Comment by ykoush** [comment]
No, but similar - all to be specified by @TheAmid

**Comment by tiborauer** [comment]
So the point is to give an updated estimate rather then compare it against those in 2017.

**Comment by ykoush** [comment]
Right, I slightly rephrased the initial comment. I think it is all specific to a local PC and applied modifications. The new release is coming soon, but there are no planned major time-affecting developments. More formal check should also be published later.

**Comment by TheAmid** [comment]
Tests were conducted using testRTexp.py for simulation of real-time data export on a desktop PC (Intel Core i7-8700, 3.2GHz, 6 cores, 12 threads, 16 GB 2666 MHz RAM, 250 GB SSD, Win 10). Time vectors were analyzed using analyzeEventRecords.m function. m2017p35 – Matlab 2017a and Python 3.5.2. m2019p36 – Matlab 2019b and Python 3.6.0. Elapsed time (ms) – elapsed processing time (visualization not included, Koush et al., 2017, Neuroimage).

Intermittent
m2017p35: Elapsed time mean = 477.4, std = 27.8
m2019p36: Elapsed time mean = 475.8, std = 26.4
		      t2-t1	t3-t2	t4-t3	t5-t4	t7-t6(in)	t7-t6(fb)	t9-t7(in)	t9-t7(fb)	tAbs(in)	tAbs(fb)
m2017p35	1.5	379.3	8.9	1.7	0.6	0.6	141.6	8.0	141.7	7.8
m2019p36	1.5	378.4	9.0	2.1	0.6	0.6	141.5	7.6	141.3	7.5

Continuous
m2017p35: Elapsed time mean = 502.7, std = 28.9
m2019p36: Elapsed time mean = 480.7, std = 21.0
		       t2-t1	t3-t2	t4-t3	t5-t4	t8-t5	t10-t8	tAbs(fb)
m2017p35	2.7	393.2	10.2	2.0	4.3	6.4	6.4
m2019p36	1.4	380.6	9.3	2.2	3.3	6.2	6.0

SVM
m2017p35: Elapsed time mean = 597.8, std = 26.3
m2019p36: Elapsed time mean = 600.0, std = 26.1
		      t2-t1	t3-t2	t4-t3	t5-t4
m2017p35	3.8	485.1	9.4	1.7
m2019p36	2.7	486.0	9.8	2.1

TASK
m2017p35: Elapsed time mean = 977.3, std = 103.1
m2019p36: Elapsed time mean = 966.4, std = 98.7
		       t2-t1	t3-t2	t4-t3	t5-t4
m2017p35	6.0	792.8	12.2	2.0
m2019p36	6.5	789.9	13.0	2.2

**Comment by ykoush** [comment]
To conclude, we did not observe principal time differences when upgrading Python and Matlab to the specified versions.
