### ISSUE TITLE
cannot import name config

### ISSUE THREAD

**Issue by shan-donahue** [OpenNFT/OpenNFT#79]
Hello I am using python 3.6 and MATLAB R2020a which I am seeing other people have success with, but I have run some pip installs and I am having an error -> ImportError: cannot import name 'config' I have been trying to find an answer but I am wondering if anyone here can help me out. I greatly appreciate any advice

**Comment by tiborauer** [comment]
At which step do you have the error?

**Comment by shan-donahue** [comment]
Ive already set up python 3.6 as a virtual environment set up matlab and am trying to just run the opennft so Im running python ./opennft I am on macOS. I have had missing modules come up and installed all of those but now it just prints out the ImportError message.

**Comment by tiborauer** [comment]
>running python ./opennft

I guess you mean typing  `python ./opennft`, which is not approriate. 
You should simply type `opennft` (see [here](https://github.com/OpenNFT/OpenNFT#running-opennft-application))

**Comment by shan-donahue** [comment]
Thank you I actually got it working with the pycharm settings in that link instead of using the terminal! thhe help was much appreciated

**Comment by espdev** [comment]
Running from terminal: `python -m opennft`
