### ISSUE TITLE
File not found error + NoneType error

### ISSUE THREAD

**Issue by PinkInk22** [OpenNFT/OpenNFT#80]
Hello I am currently running opennft I followed the instructions and am running miniconda python3.6 on windows 10 with matlab R2020a. when I do run the program I get some tracebacks that state:
 TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
But it does want me to initialize MATLab and I did try that but I get a file not found error: 
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\PATH TOO \\miniconda3\\envs\\opennft_venv\\lib\\site-packages\\opennft\\plugins'

**Comment by ykoush** [comment]
It seems that the path is not specified properly. Otherwise, please try to follow the installation steps that we cartooned in Presentation number 4 under https://github.com/OpenNFT/Courses/releases/tag/1.0
You may find other presentations useful as well.
Other ideas from @espdev  ?

**Comment by espdev** [comment]
|  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\PATH TOO \miniconda3\envs\opennft_venv\lib\site-packages\opennft\plugins'

It seems to me we forgot to add "plugins" directory to package/package_data in setup.py script.
@PinkInk22 could you try to install OpenNFT in editable mode?
```
pip install -e path\to\opennft\project\directory
```

**Comment by PinkInk22** [comment]
I believe having it in editable worked the app is launched and when I hit initialize more options in the application do actually open up and I do get some tracebacks however and I wanted to see if this was something to worry about


TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\Shannon My Love\miniconda3\envs\OpenNFT_venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\Shannon My Love\miniconda3\envs\OpenNFT_venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\Shannon My Love\miniconda3\envs\OpenNFT_venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
2020-07-13 09:40:08 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_MAIN_81406" helper process 9136...
2020-07-13 09:40:16 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_MAIN_81406" is started
2020-07-13 09:40:16 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_MAIN_81406"
2020-07-13 09:40:18 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_SPM_81406" helper process 14876...
2020-07-13 09:40:28 | INFO      | mlproc:_start_matlab - Matlab engine "MATLAB_NFB_SPM_81406" is started
2020-07-13 09:40:28 | INFO      | mlproc:_connect - Connected to Matlab engine "MATLAB_NFB_SPM_81406"
2020-07-13 09:40:30 | INFO      | mlproc:_start_matlab - Starting Matlab engine "MATLAB_NFB_PTB_81406" helper process 13124...

I copy and pasted the above from my command line

**Comment by ykoush** [comment]
I think this is something new wrt this 'TypeError: ...'. I recently tried it with one colleague and openNFT seems working regardless this TypeError, just go ahead with demo and ignore it for now. We will try to find out more.

**Comment by PinkInk22** [comment]
Thank you, I have been running through the tutorial and have initialized the software and added in the NF_PSC_int_155.ini, Parameters appear to be set up as in the demo videos which are slightly different due to the version updates and have it set to offline mode. When I hit set up I do get that the first file path to 001_000007_000001.dcm does exist in the MRI watch folder however in my terminal I get the following error message: 
Error using loadjson (line 79)
input file does not exist

Error in loadProtocolData (line 23)
prt = loadjson(jsonFile);

**Comment by ykoush** [comment]
Of course, you have to justify the paths in setup card or .ini (keep the file separator '//').

**Comment by PinkInk22** [comment]
in the NF_PSC_int_155.ini file I have the the watchfolder path set to where I placed the demo data. I ended up creating  a folder _RT under the C drive to match the path specified in the folder along with the video is this what you are referring to?

**Comment by PinkInk22** [comment]
at the bottom it is currently saying I am missing: \OpenNFT\opennft\matlab\utils\loadProtocolData.m, line 23, in loadProtocolData
input file does not exist

**Comment by da0c** [comment]
Please check, that you have correct JSON (.json) file with protocol definition, and the path to this file is correctly specified in .ini file, as Yory said earlier.
Also, you can put a breakpoint in Matlab and check the file path in debug mode.

**Comment by ykoush** [comment]
If you are missing loadProtocolData.m, unfortunately it looks like a wrong installation or a mess that occurred later. Do you have someone to help you locally? Otherwise I can try to help you via shared screen if you send me a regular email at opennft@gmail.com

**Comment by da0c** [comment]
@ykoush, as far as I understand, the problem is in the missing input file for loadProtocolData (.json), not the loadProtocolData.m file itself.

**Comment by PinkInk22** [comment]
Hello, I had sent an email earlier today to the email you had specified I was wondering if you received it?

**Comment by ykoush** [comment]
Yes, answered there.

**Comment by da0c** [comment]
The problem was in the newest version 0.11.0 of pyqtgraph.
I've changed `pyqtgraph == 0.10.0` in requirements.txt.
Reinstall pyqtgraph by `pip` also fixes the problem:
`pip install pyqtgraph==0.10.0`

**Comment by da0c** [comment]
Created bugreport on `pyqtgraph`:
https://github.com/pyqtgraph/pyqtgraph/issues/1353
