### ISSUE TITLE
file identification problem with shared.dat during memory map initialization (initmemmap)

### ISSUE THREAD

**Issue by lucp88** [OpenNFT/OpenNFT#83]
Hi, 

I'm running a NFB study using OpenNFT (not the latest version but already with the rtQA implemented) and I'm experiencing the following issue on NFB runs 2 and up.

If, after the first NFB run I increase the run and dcm number from the interface, the toolbox crashes on the first volume of the new run. It throws a file identification error originating from the initmemmap.m function where, as it turns out, matlab doesn’t get writing permission during fopen(fn, ‘w’) (returns -1). It specifically concerns the 'shared.dat' file. My workaround is when launching the next run with the updated run and dcm nr's, I start the session (without MRI acquisition), quickly close it and than launch it again (run nr and dcm nr unchanged) WITH MRI input. So i will open and close a session without data acquisition before running the actual session/new run.

The problem seems to be machine specific, as i cannot reliably recreate the error on another PC.  In addition it is my impression that the onset of the problem coincided with changing to a new and more powerful PC at the scanner.

Perhaps any of you can shed their lights on this. Any information is very much appreciated! Many thanks in advance.

(I don't have the error details right now but will save it the next time it occurs).

Cheers, 

Lucas

**Comment by lucp88** [comment]
Hi, 

After merging the latest changes made to OpenNFT with my own copy, the issue seems to have disappeared. No idea why..

Lucas

**Comment by ykoush** [comment]
I think this is because you got an intermediate rtQA work in progress version, we where working around shared files at some point, right @da0c , @TheAmid ?
