### ISSUE TITLE
error with demo files: Index in position 3 exceeds array bounds (must not exceed 42)

### ISSUE THREAD

**Issue by eniluap** [OpenNFT/OpenNFT#86]
Hello, 
I am using OpenNFT under Ubuntu 16.04 / Python 3.6 / Matlab 2018a.
I successfully installed the software and I am now trying to run the demo. 
The initialization works well but I am getting the following error when I try to start the experiment: 

Thank you for your help.
P.

home/XXXXXX/NEUROFEEDBACK/demo_openNFT/OpenNFT_DemoData/NF_PSC/NF_Run_1/001_000007_000001.dcm
Index in position 3 exceeds array bounds (must not exceed 42).

Error in vol3Dimg2D (line 27)
                  sx*dim3D(1) + 1:(sx+1)*dim3D(1)) = rot90(vol3D(:,:,sl));

Error in setupFirstVolume (line 92)
imgViewTempl = vol3Dimg2D(imgVolTempl, slNrImg2DdimX, slNrImg2DdimY, ...

Traceback (most recent call last):
  File "/home/XXXXXX/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 762, in callMainLoopIteration
    self.eng.setupFirstVolume(fname, nargout=0)
  File "/home/XXXXXX/.local/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/home/XXXXXX/.local/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/home/XXXXXX/.local/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /home/XXXXXX/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/utils/vol3Dimg2D.m, line 27, in vol3Dimg2D

  File /home/XXXXXX/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/setupFirstVolume.m, line 92, in setupFirstVolume
Index in position 3 exceeds array bounds (must not exceed 42).

**Comment by TheAmid** [comment]
Hi!

It seems there are problems with parameters, please double check paths and settings for selected feedback type.

Did you run continuous or intermittent PSC?

**Comment by ykoush** [comment]
Also, different Demo data may have different dimensions so you have to keep them consistent when setting on your PC, similarly as in original .ini files under ./configs. Otherwise, let us know.

**Comment by eniluap** [comment]
Thanks. It was indeed a mistake with the settings parameters.
