### ISSUE TITLE
Bug in OpenNFT.ui

### ISSUE THREAD

**Issue by DirkSchomburg** [OpenNFT/OpenNFT#95]
Trying to load the file ...\OpenNFT\opennft\ui\opennft.ui with the QT Designer gives the error:

An error has occurred while reading the UI file at line 546, column 100: Unexpected element item.

**Comment by da0c** [comment]
Hope, I've fixed it. Please check.

**Comment by DirkSchomburg** [comment]
Thank you, it works now.

with kind regards
Dirk Schomburg

Von: Artem Nikonorov [mailto:notifications@github.com]
Gesendet: Montag, 7. Dezember 2020 20:17
An: OpenNFT/OpenNFT <OpenNFT@noreply.github.com>
Cc: Schomburg, Dirk <dirk.schomburg@med.ovgu.de>; Author <author@noreply.github.com>
Betreff: Re: [OpenNFT/OpenNFT] Bug in OpenNFT.ui (#95)


Hope, I've fixed it. Please check.
