### ISSUE TITLE
Issue preprVol.m Bad output array

### ISSUE THREAD

**Issue by Pamela281** [OpenNFT/OpenNFT#96]
Hello, 

I'm running OpenNFT under Windows 10, with MATLAB 2019b and Python 3.6. I installed OpenNFT using PyCharms. 
I try to run the "NF_PSC_int_155.ini" demo: initialization works well, as well as the setup. However, when I start the demo, I have this error: 

> Error using spm_conv_vol
Bad output array.

>Error in spm_smooth>smooth1 (line 107)
spm_conv_vol(P,Q,x,y,z,-[i,j,k]);

>Error in spm_smooth (line 40)
    smooth1(P,Q,s,dtype);

>Error in preprVol (line 180)
spm_smooth(reslVol, smReslVol, gKernel);

>Traceback (most recent call last):
  File "C:\Users\pamel\PycharmProjects\OpenNFT\opennft\opennft.py", line 778, in callMainLoopIteration
    self.eng.preprVol(fname, self.iteration, nargout=0)
  File "C:\Users\pamel\PycharmProjects\OpenNFT\venv\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "C:\Users\pamel\PycharmProjects\OpenNFT\venv\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "C:\Users\pamel\PycharmProjects\OpenNFT\venv\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File C:\Program Files\MATLAB\R2019b\toolbox\spm12\spm_smooth.m, line 107, in smooth1

 > File C:\Program Files\MATLAB\R2019b\toolbox\spm12\spm_smooth.m, line 40, in spm_smooth

 > File C:\Users\pamel\PycharmProjects\OpenNFT\opennft\matlab\nfbPreprVol\preprVol.m, line 180, in preprVol
Bad output array.

Does someone know how to fix it? 
Thanks a lot for your help

**Comment by ykoush** [comment]
Please double check all settings on the Settings card - you have to properly modify all paths depending where you copied the data and keep in mind that each Demo feedback type uses its own settings. You could also set a debug on Error in preprVol (line 180) and see the variables, seemingly reslVol is already corrupted, which could be due to improper settings for Demo.

**Comment by Pamela281** [comment]
I've checked all the parameters (see photo), I don't see where the error could be 

![image](https://user-images.githubusercontent.com/60964329/101877787-db906400-3b8e-11eb-9aa7-9926e4bc12de.png)

**Comment by Pamela281** [comment]
It works ! Thanks a lot
