### ISSUE TITLE
need for Matlab Statistics and Machine Learning Toolbox?

### ISSUE THREAD

**Issue by eniluap** [OpenNFT/OpenNFT#97]
Hello, 
I'm trying to run the demos but I got the following error when try NF_PSC_cont_155.ini
It seems that I need the Matlab Statistics ans ML toolbox but I'd like to avoid to buy it. 
Is it possible to move on without it? 
Thank you for your help.

```
'zscore' requires Statistics and Machine Learning Toolbox.

Error in setupProcParams (line 189)
P.linRegr = zscore((1:double(P.NrOfVolumes-P.nrSkipVol))');

Traceback (most recent call last):
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 1262, in setup
    self.initMainLoopData()
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 564, in initMainLoopData
    self.eng.setupProcParams(nargout=0)
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/setupProcParams.m, line 189, in setupProcParams
Undefined function 'zscore' for input arguments of type 'double'.
```

**Comment by tiborauer** [comment]
`zscore` should be easy to replace because a z-scoring is equivalent to subtracting mean and dividing with standard deviation.

**Comment by eniluap** [comment]
> `zscore` should be easy to replace because a z-scoring is equivalent to subtracting mean and dividing with standard deviation.

Alright, I replaced line 189 in setupProcParams.m by the following
linRegr =(1:double(P.NrOfVolumes-P.nrSkipVol))';
P.linRegr = ( linRegr - mean(linRegr(:)) ) / std(linRegr(:));

But then I have similar issue line 193 with 'mean2':
'mean2' requires Image Processing Toolbox.

Error in setupSPM (line 72)
meanVol = mean2(mean(spm_read_vols(spm_vol(P.MCTempl)),1));

Error in setupProcParams (line 193)
SPM = setupSPM(P);

Traceback (most recent call last):
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 1262, in setup
    self.initMainLoopData()
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 564, in initMainLoopData
    self.eng.setupProcParams(nargout=0)
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/setupSPM.m, line 72, in setupSPM

  File /Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/setupProcParams.m, line 193, in setupProcParams
Undefined function 'mean2' for input arguments of type 'double'.

**Comment by tiborauer** [comment]
That line can be replaced with 

meanVol = mean(spm_read_vols(spm_vol(P.MCTempl)),'all');

**Comment by da0c** [comment]
I think it's a good idea to replace `zscore` and `mean2` in our code.

**Comment by eniluap** [comment]
> That line can be replaced with
> 
> meanVol = mean(spm_read_vols(spm_vol(P.MCTempl)),'all');

Thanks. Sorry, but then there is another issue:

```
'bwperim' requires Image Processing Toolbox.

Error in helperPrepareOrthView>getOrthROIs (line 342)
    tmpt = double(bwperim(tmpt,4));

Error in helperPrepareOrthView>redrawall (line 208)
                           getOrthROIs(imgt, imgc, imgs, ROIs, coordParam);

Error in helperPrepareOrthView (line 73)
    [imgt, imgc, imgs] = redrawall(displBackgr.vol,displBackgr.mat, ...

Traceback (most recent call last):
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 1262, in setup
    self.initMainLoopData()
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/opennft.py", line 583, in initMainLoopData
    self.engSPM.helperPrepareOrthView(self.spmHelperP, 'bgEPI', nargout=0)
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/utils/helperPrepareOrthView.m, line 342, in getOrthROIs

  File /Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/utils/helperPrepareOrthView.m, line 208, in redrawall

  File /Users/eniluap/opt/anaconda3/envs/OpenNFT_venv/lib/python3.6/site-packages/opennft/matlab/utils/helperPrepareOrthView.m, line 73, in helperPrepareOrthView
Undefined function 'bwperim' for input arguments of type 'double'.
```

**Comment by tiborauer** [comment]
I am afraid I cannot help with that... It is, indeed, an image processing function.

**Comment by ykoush** [comment]
The purpose of this function was to add a contour of the ROI to the orthogonal plot on a mouse click in GUI viewer, during Preparation step. There are a few possible solutions, if you ultimately cannot get an Image Processing Toolbox. But I just realized that quite a big part of helperPrepareOrthView.m appears redundant since we recently moved visualizations and overlays to Python including bwperim function. We will clean it in the next commit, actually I think we can get rid of both Matlab Toolboxes.
For now, just change the mode in this function, l. 67 to "strParam.modeDispl = [0 1 0];". Let us know if there is anything else in Matlab to stop you.

**Comment by espdev** [comment]
@ykoush we are getting ROI boundaries from MATLAB side.

https://github.com/OpenNFT/OpenNFT/blob/34a6d60e735cc74d4fbd69c602dfbb63e8e29f4f/opennft/opennft.py#L1733-L1735

It is not a redundant code. If we want to delete `bwperim` and Image Processing Toolbox dependency, we need to implement this functionality on Python side using functions and morphological algorithms from scikit-image package for example.

**Comment by ykoush** [comment]
Right, Sorry, I was just looking for bwperim in helperPrepare, but we also have boundaries = bwboundaries(roi, 8, 'holes'); in helperUpdate that I missed, just another implementation. So then we could provide just a cut of the roi from Matlab before taking the contour, and get to the contour in Python.

**Comment by ykoush** [comment]
Then for a quick solution you should be able to select another mode as I wrote and disable display of ROIs by setting USE_ROI = False in config.py. This should disable display of ROIs completely until we move it to Python, to get more independent code form Matlab, which make sense. Alternatively, you can try to implement a display of blob by taking away the contour operations, but this will not let you see the activity under it..

**Comment by eniluap** [comment]
Thank you for your answers. 
I changed the display mode and set USE_ROI to False. However I am also having trouble with the %get roi contour part : 

```
Error in helperPrepareOrthView>getOrthROIs (line 342)
    tmpt = double(bwperim(tmpt,4));

Error in helperPrepareOrthView>redrawall (line 208)
                           getOrthROIs(imgt, imgc, imgs, ROIs, coordParam);

Error in helperPrepareOrthView (line 73)
    [imgt, imgc, imgs] = redrawall(displBackgr.vol,displBackgr.mat, ...
```

Is it possible to disable it?

**Comment by TheAmid** [comment]
> Thank you for your answers.
> I changed the display mode and set USE_ROI to False. However I am also having trouble with the %get roi contour part :
> 
> ```
> Error in helperPrepareOrthView>getOrthROIs (line 342)
>     tmpt = double(bwperim(tmpt,4));
> 
> Error in helperPrepareOrthView>redrawall (line 208)
>                            getOrthROIs(imgt, imgc, imgs, ROIs, coordParam);
> 
> Error in helperPrepareOrthView (line 73)
>     [imgt, imgc, imgs] = redrawall(displBackgr.vol,displBackgr.mat, ...
> ```
> 
> Is it possible to disable it?

You could comment out lines 342, 343 and 344 to avoid using Image Processing Toolbox in this function. It could help in this case.
