### ISSUE TITLE
Feature proposal: ICA 

### ISSUE THREAD

**Issue by tiborauer** [OpenNFT/OpenNFT#99]
Is there an ongoing project or plan to implement rt-ICA either based on [FastICA ](https://research.ics.aalto.fi/ica/fastica/code/dlcode.shtml), [SparseFastICA](https://uk.mathworks.com/matlabcentral/fileexchange/54560-sparsefastica-for-fmri-data-analysis) or any other approach?

**Comment by ykoush** [comment]
Any novel and justified and/or (to be)published implementations are welcome.

**Comment by tiborauer** [comment]
I was rather asking whether you are aware of any ongoing project implementing ICA in OpenNFT. Do you have any experience with real-time ICA?

**Comment by ykoush** [comment]
I don't know if somebody is doing rt-ICA with OpenNFT. I also didn't try it.

**Comment by JordantherGin** [comment]
github has numerous NFT SDK's
